# SITE CONFIGURATION
baseurl: ""
url: "https://blog.samuelorji.com"
show_drafts: false


# Header and footer text
header_text: ♡
header_feature_image: assets/img/pexels/triangular.jpeg
footer_text: >
  Copyright © 2018-2022 Samuel Orji -- Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap!</a> <a rel="me" href="https://pony.social/@thephd"></a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png    


title: Samuel's blog
avatar: assets/images/giraffe-favicon.png
favicon: assets/images/giraffe-favicon.png
# header_text: Samuel Orji's blog - Nerd that writes about programming and things he has learnt or is learning.
#   All things #Scala and #Rust
header_feature_image: assets/images/laptop-from-above.jpg
email: awesomeorji@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Samuel Orji's blog - Nerd that writes about programming and things he has learnt or is learning.
  All things #Scala and #Rust
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: eat_then_sleep
github_username:  samuelorji


# BLOG CONFIGURATION
post_navigation: true
paginate: 10
paginate_path: "blog/page:num"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
# Build settings
theme: type-on-strap
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
