# SITE CONFIGURATION
baseurl: ""
url: "https://samuelorji.github.io"
show_drafts: false


# Header and footer text
header_text: ♡
header_feature_image: assets/img/pexels/triangular.jpeg
footer_text: >
  Copyright © 2018-2022 Samuel Orji -- Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap!</a> <a rel="me" href="https://pony.social/@thephd"></a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png    


title: Samuel's blog
avatar: assets/images/giraffe-favicon.png
favicon: assets/images/giraffe-favicon.png
# header_text: Samuel Orji's blog - Nerd that writes about programming and things he has learnt or is learning.
#   All things #Scala and #Rust
header_feature_image: assets/images/laptop-from-above.jpg
email: awesomeorji@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Samuel Orji's blog - Nerd that writes about programming and things he has learnt or is learning.
  All things #Scala and #Rust
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: eat_then_sleep
github_username:  samuelorji


# BLOG CONFIGURATION
post_navigation: true
paginate: 10
paginate_path: "blog/page:num"
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
# Build settings
remote_theme: sylhare/Type-on-Strap 
plugins:
  - jekyll-feed

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github

